ALTER TABLE public.demandas
  ADD COLUMN rede TEXT NOT NULL DEFAULT '',
  ADD COLUMN horario TEXT NOT NULL DEFAULT '',
  ADD COLUMN tarefas_total INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN tarefas_concluidas INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN check_in_at TIMESTAMPTZ NULL,
  ADD COLUMN check_in_by TEXT NOT NULL DEFAULT '';
